### ISSUE TITLE
Add some explanation of how the reminders work and how we use the data

### ISSUE THREAD

**Issue by johanehr** [johanehr/parking-reminder-frontend#25]
This is meant to explain the feature itself, and put any worries to rest regarding misuse of personal data/Privacy Policy (possibly going into some technical detail, which might be good for portfolio purposes).

AC:
- Update the NextJS frontend with some explanatory material

**Comment by frankosgit** [comment]
Take a look at the privacypolicymodal branch when you get time :), not finished but a start. I'm thinking the modal can be reused in the input form too.
